spring.application.name=makeitnas

spring.h2.console.enabled=true
spring.h2.console.path=/Users

spring.datasource.url=jdbc:h2:mem:MakeItNAS
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database=h2
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/test-docs